version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: test123!
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  hasura:
    image: hasura/graphql-engine:v2.0.9
    depends_on:
      - postgres
    restart: always
    ports:
      - '8080:8080'
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://test:test123!@postgres:5432/test
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"

volumes:
  postgres-data:
